# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6wKyMkrKknCRgqGbNoXEnVhBVdBb1jg
"""

import streamlit as st
import tensorflow as tf
import streamlit as st
from tensorflow.keras.preprocessing.image import load_img, img_to_array

#comment

def load_model():
  model=tf.keras.models.load_model('/content/drive/MyDrive/Hand_digit/final_model.hdf5')
  return model
model=load_model()

st.write("""
         # SignDigit Prediction
         """
         )

file = st.file_uploader(" upload your file here", type=["jpg"])
import cv2
from PIL import Image, ImageOps
import numpy as np
def import_and_predict(image_data, model):

        size = (64, 64)
        example_image = ImageOps.fit(image_data, size, Image.ANTIALIAS)
        example_image_array = img_to_array(example_image)
        preprocessed_ex_image = example_image_array / 255.0
        preprocessed_ex_image = np.expand_dims(preprocessed_ex_image, axis=0)
        prediction = model.predict(preprocessed_ex_image)
        predicted_class = prediction.argmax(axis=-1)

        return predicted_class

if file is None:
    st.text("Please upload an image file")
else:
    image = Image.open(file)
    st.image(image, use_column_width=True)
    predictions = import_and_predict(image, model)
    string = "This image most likely is:" + predictions[0]
    st.success(string)

